spring:
  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://ccpa7stkruda3o.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com/ddpiskfou6a8t4
    username: u5tdddt2ka3aqj
    password: p8fbc995eb60a15547be9f7b340d787b3d86d7568790bb36e7bfb27d31c888a1d
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres

jwt:
  secret-key: bluuminn.sns-application-2023.secret_key
  token:
    # 30 days
    expired-time-ms: 2592000000